"""add email to items

Revision ID: 67d26b6f6c95
Revises: 9789f81c9864
Create Date: 2025-10-25 22:59:49.828379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d26b6f6c95'
down_revision: Union[str, Sequence[str], None] = '9789f81c9864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'email')
    # ### end Alembic commands ###
